### ISSUE TITLE
Newbie information

### ISSUE THREAD

**Issue by ccondrup** [dalexandrov/PowershellEditor#1]
Hi, this looks really promising!
I'd just like to know:
1. how to install+activate it
2. which Eclipse versions it is compatible with
3. Is there an update site for this already

**Comment by smasala1** [comment]
putting the plugin inside the eclipse dropins folder gives me the following error when trying to edit a ps1 file.

java.lang.ClassNotFoundException: org.powershell.editors.PowershellEditor
    at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:513)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:429)
......................

**Comment by dalexandrov** [comment]
I am really sorry for a VERY long pause! 
There is an update site: http://dalexandrov.github.io/PowershellEditor/
..and now it is published to eclipse marketplace: https://marketplace.eclipse.org/content/powershelleditor

This should fix all issues.

Thank you,
regards,

Dmitry
