### ISSUE TITLE
Update MP Entry with feature id

### ISSUE THREAD

**Issue by paulvi** [dalexandrov/PowershellEditor#3]
please update MP entry https://marketplace.eclipse.org/content/powershelleditor with feature id

That will enable install via MPC (e.g. drag-n-drop)

**Comment by dalexandrov** [comment]
Done! 
Thank you very much!!

Regards,

Dmitry

From:  Paul Verest notifications@github.com
Reply-To:  dalexandrov/PowershellEditor
<reply+i-37363597-98e57b05562cea7feb7e1d08f7d07df16b0378c0-2016949@reply.git
hub.com>
Date:  âòîðíèê, 8 èþëÿ 2014 ã., 16:08
To:  dalexandrov/PowershellEditor PowershellEditor@noreply.github.com
Subject:  [PowershellEditor] Update MP Entry with feature id (#3)

please update MP entry
https://marketplace.eclipse.org/content/powershelleditor with feature id

That will enable install via MPC (e.g. drag-n-drop)

—
Reply to this email directly or view it on GitHub
https://github.com/dalexandrov/PowershellEditor/issues/3 .

**Comment by paulvi** [comment]
thanks
