### ISSUE TITLE
code completion form other files doesn't seem to work

### ISSUE THREAD

**Issue by rogermartensson** [dalexandrov/PowershellEditor#6]
Am running on Eclipse 4.2.2 and I can't get it to work.

When I first noticed this I was working on a module but I get the same problem when using two single PS1-files in the root of the project. (file1.ps1 dot-sources file2.ps1)

**Comment by dalexandrov** [comment]
Unfortunately I haven't tried it on this version. I need some time for this.

**Comment by rogermartensson** [comment]
I'm closing this issue since it's too old.
